title: Welcome!
author: Emily Alvarado
email: z1833226@students.niu.edu
description: > # this means to ignore newlines until "baseurl:"
  This will be my personal blog for all of my current and future projects. I will showcase my work and discuss my research. I hope you enjoy!

# social links
github_username:  emilyalvarado # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
